### ISSUE TITLE
network dirs need to be mounted in dev console

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#193]
This mostly needs to be implemented in the dev hook, but I imagine we'll need to update the dev payload to include mount payload like we do in code configure.

**Comment by lyondhill** [comment]
In the code configure we look through the boxfile for the network mount locations
```yaml
web.site:
  network_dirs:
    data.files:
      - path/to/directoryA
```
 to make the process work the same way we will be looking in the boxfile under the dev node
```yaml
dev:
  network_dirs:
    data.files:
      - path/to/directoryA
```
