### ISSUE TITLE
Missing requested PHP extensions

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#240]
From my `boxfile.yml`:

```yaml
code.build:
  engine: php
  config:
    document_root: /web
    apache_modules:
      - authz_host

    runtime: php-5.6
    extensions:
      - fileinfo
      - filter
      - gd
      - hash
      - json
      - mysqli
      - openssl
      - pcre
      - session
      - soap
      - SPL
      - xml
      - zip
      - zlib
    dev_zend_extensions:
      add:
        - xdebug
      rm:
        - opcache
```

I see the following after `nanobox dev run`:

```$ php -m
[PHP Modules]
Core
date
ereg
libxml
mysqlnd
openssl
pcre
Reflection
SPL
standard

[Zend Modules]
```

Accessing the app via web fails due to `json_decode()` being undefined.
