### ISSUE TITLE
Destroying docker container fails with "dev run" on Windows 10

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#250]
With the following `boxfile.yml` ...

```yaml
code.build:
  engine: php
  config:
    document_root: /web
    apache_modules:
      - authz_host

    runtime: php-5.6

web.site:
  start:
    fpm: start-php
    apache: start-apache

data.mysql:
  image: nanobox/mysql:5.6
```

... I see the following very often on Windows 10:

```
>nanobox dev run

------------------------------------
Running the following prerequisites:

$ nanobox build
$ nanobox dev deploy

------------------------------------

+ (nanobox build) :
  + Preparing environment :
    √ Mounting codebase
  + Building runtime :
    √ Starting docker container
    √ Preparing environment for build
    √ Gathering requirements
    √ Mounting lib_dirs
    √ Installing binaries and runtimes
    √ Packaging build

+ (nanobox dev deploy) :
  + Preparing environment :
    √ Mounting codebase
  + Syncing data components :
    + Removing old :
      + data.mysql :
        ! Destroying docker container

Error   : cannot unmarshal array into Go value of type types.ContainerJSON
Context : failed to sync components -> failed to purge delta components -> failed to destroy component -> failed to remove docker container -> json
```

Sometime restarting after `nanobox implode` helps.
