### ISSUE TITLE
Support custom components

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#365]
It would be useful if one could add custom components simply based on Docker images. Something like this:

```yaml
web.site:
  # ...

custom.selenium:
  image: selenium/standalone-chrome
```

I'm not sure this is already possible with [custom images](https://docs.nanobox.io/images/).

This is a more general approach to the issue mentioned in #364 which could a) solve a huge chunk of problems and b) open a huge can of worms. ;-)
