### ISSUE TITLE
File watcher on Windows doesn't respond

### ISSUE THREAD

**Issue by tsnuer** [nanobox-io/nanobox#389]
Our boxfile.yml currently looks like this: 
```
run.config:
  engine: nodejs
  fs_watch: true
  engine.config:
    runtime: nodejs-5.8
    dep_manager: npm

  cache_dirs:
    - node_modules

  extra_steps:
    - npm install
```

Everything works perfectly on MacOS, but on Windows the build process that we put in place doesn't work. 
After talking with @tylerflint, we got a workaround that using `nanobox run touch FILE_THAT_TRIGGERS_BUILD` and it works on all platforms. It's a good workaround but still asks the dev to remember to run this every time. 

Is there an issue with windows or could it just be an isolated case?
