### ISSUE TITLE
Problem reaching Go app

### ISSUE THREAD

**Issue by hasit** [nanobox-io/nanobox#450]
I am trying to deploy a Go application that uses Echo. Here is the repo for reference - https://github.com/hasit/healthyrepo.

This is my boxfile.yml:

```yml
run.config:
  engine: golang
  engine.config:
    runtime: go-1.8
    package: 'github.com/hasit/healthyrepo'
    fetch: 'go get'
    build: 'go build'

web.api:
  start: healthyrepo
```

I see my component on the dashboard as shown in the screenshot below:

<img width="1158" alt="screen shot 2017-05-24 at 10 51 04 pm" src="https://cloud.githubusercontent.com/assets/1553055/26437707/8a0af96a-40d3-11e7-980e-ef00141587c0.png">

When I try to access it, I get the follow log message repeatedly:

```
2017/05/25 05:48:54 http: proxy error: dial tcp 192.168.0.9:8080: getsockopt: connection refused
```

What am I doing wrong?
