### ISSUE TITLE
Feature request: imports/includes in boxfile.yml

### ISSUE THREAD

**Issue by kristoftorfs** [nanobox-io/nanobox#589]
It would be convenient to have reusable yaml files to include in our boxfile.yml. Preferably even separated per alias (local, dry-run, prod, ...) and allowing online files (e.g. from GitHub repositories) so they can be kept in source control.

An example:

```yaml
imports:
  all:
    - https://raw.githubusercontent.com/my-user/my-rep/master/symfony.yml
  local:
    - https://raw.githubusercontent.com/my-user/my-rep/master/mailcatcher.yml

run.config:
  engine: php
  engine.config:
    runtime: php-7.1
    webserver: nginx
    document_root: web
    ...
```
