### ISSUE TITLE
Can't deploy. NoMethodError

### ISSUE THREAD

**Issue by NullVoxPopuli** [nanobox-io/nanobox#647]
This is new. I was able to deploy yesterday.
```
$ nanobox deploy
Root privileges are required to start the server. Your system password may be requested...
[sudo] password for localusername: 
Skipping (already running) :
Preparing environment :

Compiling application :
  Starting docker container :
  Preparing environment for compile :
    - Copying ssh keys into the build environment...
    - Setting up directories and permissions...
    /opt/gonano/hookit/lib/hookit/hook.rb:91:in `method_missing': undefined method `each_pair' for nil:NilClass (NoMethodError)
    	from /opt/nanobox/hooks/lib/hash.rb:7:in `deep_merge!'
    	from /opt/nanobox/hooks/lib/hash.rb:3:in `deep_merge'
    	from /opt/nanobox/hooks/boxfile:51:in `<main>'

Error   : failed to execute hook (boxfile) on 4b0f45c2154dd34a524205bc7e9406879e9d1f456b5c0b6480da9bd7854fcf54: util:Exec:/opt/nanobox/hooks/boxfile: bad exit code(1): 
Context : failed to compile the code -> failed to run the (compile)boxfile hook
```

boxfile:
```yaml
run.config:
  engine: ruby
  engine.config:
    runtime: ruby-2.4

  # add extra packages
  extra_packages:
    - nginx
    - nodejs
    - gettext-tools

  build_triggers:
    - Gemfile
    - Gemfile.lock

deploy.config:
  before_live:
    web.main:
      - rake db:schema:setup_or_migrate
  transform:
    - chown -R gonano:gonano /app/tmp
    - envsubst '$S3_BUCKET:$NGINX_PORT' < /app/deployment/nginx.template.conf > /app/deployment/nginx.conf

# PG DB
data.db:
  image: nanobox/postgresql
  cron:
    - id: backup
      schedule: '0 3 * * *'
      command: 'bash /app/deployment/production/backup-db'

# CACHE
data.redis:
  image: nanobox/redis:3.0

# API
web.main:
  start:
    puma: bundle exec puma -C ./config/puma.rb -b unix:///app/sockets/puma.sock
    nginx: /app/deployment/start-nginx

  writable_dirs:
    - tmp
    - log
    - sockets
    - public

  # the path to a logfile you want streamed to the nanobox dashboard
  log_watch:
    rails: 'log/production.log'
    nginx: 'log/nginx.access.log'
    nginx_error: 'log/nginx.error.log'

# SIDEKIQ
worker.jobs:
  start: bundle exec sidekiq

  # add writable dirs to the web component
  writable_dirs:
    - tmp
    - log

  log_watch:
    sidekiq: 'log/sidekiq.log'
```
