### ISSUE TITLE
http: proxy error: dial tcp

### ISSUE THREAD

**Issue by ayelen117** [nanobox-io/nanobox#689]
Hello, 
I having the next problem and I can´t to run the application:
`http: proxy error: dial tcp 192.168.0.20:8080: connect: connection refused`

This is my boxfile:
```
run.config:
  engine: php

  engine.config:
    runtime: php-7.1

    cache_dirs:
      - vendor
      - packages
      - node_modules

    document_root: public

    extensions:
      - pdo
      - mbstring
      - tokenizer
      - session
      - zip
      - dom
      - xml
      - ctype
      - xmlwriter
      - pdo
      - mongodb
      - pdo_mysql

    extra_steps:
      - npm install

deploy.config:
  before_live:
    web.main:
      - mkdir -p storage/framework/{sessions,cache,views}
      - php artisan migrate

data.db:
  image: nanobox/mysql:5.6

data.storage:
  image: nanobox/unfs

web.main:
  start: start-php

  writable_dirs:
    - bootstrap/cache

  log_watch:
    laravel[error]: storage/logs/laravel.log

  network_dirs:
    data.storage:
      - storage

data.mongodb:
  image: nanobox/mongodb:3.0
  config:
    objcheck: true
    log_verbosity: 'v'
    directoryperdb: true
    logappend: true
    nojournal: false
    noscripting: false
```

What am I doing wrong?  

Thanks in advance.

**Comment by danhunsaker** [comment]
You need to also start the web server. In this case, that's done by adding `start-apache` to your `start` section (the PHP guides show this, too, for further reference):

```yaml
web.main:
  start:
    fpm: start-php
    www: start-apache
```

Note that `fpm` and `www` there can be anything you like; those names are more for your reference than anything.
