### ISSUE TITLE
.ssh folder is not being mounted

### ISSUE THREAD

**Issue by dsandstrom** [nanobox-io/nanobox#98]
Since using v0.16.11, my .ssh folder is not being mounted.  I can't connect to an external server without a password.  My .ssh folder is in my home folder.  It worked previously (v0.16.5 I think).

_Boxfile_
```
build:
  ruby_runtime: ruby-2.2

mysql1:
  name: my_db_development
```
